### ISSUE TITLE
File not saved

### ISSUE THREAD

**Issue by rmdwirizki** [yusyaif/grader-library#1]
The file wasn't saved when I tried to call the saveScript() function.. after an hour of searching I found the problem was in the filesystem's path. so I just modify the path variable for every function in the Grader.php like this:

``` php
    $path = '/storage/scripts';
    $path =  base_path() . $path;
```

**Comment by mizwardomlank** [comment]
or you can add `base_path()` on every `/storage/`. 

just like `base_path() . '/storage/...'`
